---
- name: Configure Demo Networks in AWS
  hosts: localhost
  gather_facts: no
  vars:
    aws_region: us-east-2
    vpc_cidr: "10.0.0.0/16"
    subnets:
      - cidr: "10.0.1.0/24"
        az: "us-east-2a"
      - cidr: "10.0.2.0/24"
        az: "us-east-2a"
      - cidr: "10.0.3.0/24"
        az: "us-east-2a"
    # ami_id: "ami-0825b781215f46868" # Replace with the correct AMI ID for PA-VM-AWS-10.2.2
    # instance_type: "m5.large"
    key_name: "demo_key" # Replace with your key pair name
    security_group_name: "pa-vm-sg"

  tasks:
    - name: Create key pair
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ aws_region }}"
        state: present
      register: key_pair
      when: key_name is defined

    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: "pa-vm-vpc"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ aws_region }}"
        state: present
      register: vpc

    - name: Create Security Group
      register: security_group
      amazon.aws.ec2_group:
        name: "{{ security_group_name }}"
        description: "Security group for Palo Alto VM"
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            ports: [22, 443]
            cidr_ip: "0.0.0.0/0"
        state: present

    - name: Create Subnets
      loop: "{{ subnets }}"
      loop_control:
        loop_var: subnet
      register: created_subnets
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ aws_region }}"
        state: present
        cidr: "{{ subnet.cidr }}"
        az: "{{ subnet.az }}"
      register: created_subnets